#!/bin/sh -x
#DEBHELPER#
set -e
if [ -e /etc/kritter-tern-file-conf-postimpressionforbilling-service/run ]; then
        update-service --remove /etc/kritter-tern-file-conf-postimpressionforbilling-service
fi

