CREATE TABLE `ad_position_hourly` (
  `processing_time` datetime DEFAULT NULL,
  `impression_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pubId` int(11) DEFAULT NULL,
  `siteId` int(11) DEFAULT NULL,
  `countryId` int(11) DEFAULT NULL,
  `stateId` int(11) DEFAULT NULL,
  `cityId` int(11) DEFAULT NULL,
  `advId` int(11) DEFAULT NULL,
  `campaignId` int(11) DEFAULT NULL,
  `adId` int(11) DEFAULT NULL,
  `adpositionId` int(11) DEFAULT NULL,
  `total_request` BIGINT DEFAULT '0',
  `total_impression` BIGINT DEFAULT '0',
  `total_bidValue` double DEFAULT '0',
  `total_click` BIGINT DEFAULT '0',
  `total_win` BIGINT DEFAULT '0',
  `total_win_bidValue` double DEFAULT '0',
  `total_csc` BIGINT DEFAULT '0',
  `demandCharges` double DEFAULT '0',
  `supplyCost` double DEFAULT '0',
  `earning` double DEFAULT '0',
  `conversion` BIGINT DEFAULT '0',
  `bidprice_to_exchange` double DEFAULT '0',
  `cpa_goal` double DEFAULT '0',
  `exchangepayout` double DEFAULT '0',
  `exchangerevenue` double DEFAULT '0',
  `networkpayout` double DEFAULT '0',
  `networkrevenue` double DEFAULT '0',
  `billedclicks` double DEFAULT '0',
  `billedcsc` double DEFAULT '0',
  KEY `_impression_time` (`impression_time`),
  KEY `ad_position_hourly_pubId` (`pubId`),
  KEY `ad_position_hourly_siteId` (`siteId`),
  KEY `ad_position_hourly_countryId` (`countryId`),
  KEY `ad_position_hourly_stateId` (`stateId`),
  KEY `ad_position_hourly_cityId` (`cityId`),
  KEY `ad_position_hourly_adId` (`adId`),
  KEY `ad_position_hourly_campaignId` (`campaignId`),
  KEY `ad_position_hourly_advId` (`advId`),
  KEY `ad_position_hourly_adpositionId` (`adpositionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `ad_position_daily` (
  `processing_time` datetime DEFAULT NULL,
  `impression_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pubId` int(11) DEFAULT NULL,
  `siteId` int(11) DEFAULT NULL,
  `countryId` int(11) DEFAULT NULL,
  `stateId` int(11) DEFAULT NULL,
  `cityId` int(11) DEFAULT NULL,
  `advId` int(11) DEFAULT NULL,
  `campaignId` int(11) DEFAULT NULL,
  `adId` int(11) DEFAULT NULL,
  `adpositionId` int(11) DEFAULT NULL,
  `total_request` BIGINT DEFAULT '0',
  `total_impression` BIGINT DEFAULT '0',
  `total_bidValue` double DEFAULT '0',
  `total_click` BIGINT DEFAULT '0',
  `total_win` BIGINT DEFAULT '0',
  `total_win_bidValue` double DEFAULT '0',
  `total_csc` BIGINT DEFAULT '0',
  `demandCharges` double DEFAULT '0',
  `supplyCost` double DEFAULT '0',
  `earning` double DEFAULT '0',
  `conversion` BIGINT DEFAULT '0',
  `bidprice_to_exchange` double DEFAULT '0',
  `cpa_goal` double DEFAULT '0',
  `exchangepayout` double DEFAULT '0',
  `exchangerevenue` double DEFAULT '0',
  `networkpayout` double DEFAULT '0',
  `networkrevenue` double DEFAULT '0',
  `billedclicks` double DEFAULT '0',
  `billedcsc` double DEFAULT '0',
  KEY `_impression_time` (`impression_time`),
  KEY `ad_position_daily_pubId` (`pubId`),
  KEY `ad_position_daily_siteId` (`siteId`),
  KEY `ad_position_daily_countryId` (`countryId`),
  KEY `ad_position_daily_stateId` (`stateId`),
  KEY `ad_position_daily_cityId` (`cityId`),
  KEY `ad_position_daily_adId` (`adId`),
  KEY `ad_position_daily_campaignId` (`campaignId`),
  KEY `ad_position_daily_advId` (`advId`),
  KEY `ad_position_daily_adpositionId` (`adpositionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ad_position_monthly` (
  `processing_time` datetime DEFAULT NULL,
  `impression_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pubId` int(11) DEFAULT NULL,
  `siteId` int(11) DEFAULT NULL,
  `countryId` int(11) DEFAULT NULL,
  `stateId` int(11) DEFAULT NULL,
  `cityId` int(11) DEFAULT NULL,
  `advId` int(11) DEFAULT NULL,
  `campaignId` int(11) DEFAULT NULL,
  `adId` int(11) DEFAULT NULL,
  `adpositionId` int(11) DEFAULT NULL,
  `total_request` BIGINT DEFAULT '0',
  `total_impression` BIGINT DEFAULT '0',
  `total_bidValue` double DEFAULT '0',
  `total_click` BIGINT DEFAULT '0',
  `total_win` BIGINT DEFAULT '0',
  `total_win_bidValue` double DEFAULT '0',
  `total_csc` BIGINT DEFAULT '0',
  `demandCharges` double DEFAULT '0',
  `supplyCost` double DEFAULT '0',
  `earning` double DEFAULT '0',
  `conversion` BIGINT DEFAULT '0',
  `bidprice_to_exchange` double DEFAULT '0',
  `cpa_goal` double DEFAULT '0',
  `exchangepayout` double DEFAULT '0',
  `exchangerevenue` double DEFAULT '0',
  `networkpayout` double DEFAULT '0',
  `networkrevenue` double DEFAULT '0',
  `billedclicks` double DEFAULT '0',
  `billedcsc` double DEFAULT '0',
  KEY `_impression_time` (`impression_time`),
  KEY `ad_position_monthly_pubId` (`pubId`),
  KEY `ad_position_monthly_siteId` (`siteId`),
  KEY `ad_position_monthly_countryId` (`countryId`),
  KEY `ad_position_monthly_stateId` (`stateId`),
  KEY `ad_position_monthly_cityId` (`cityId`),
  KEY `ad_position_monthly_adId` (`adId`),
  KEY `ad_position_monthly_campaignId` (`campaignId`),
  KEY `ad_position_monthly_advId` (`advId`),
  KEY `ad_position_monthly_adpositionId` (`adpositionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `channel_hourly` (
  `processing_time` datetime DEFAULT NULL,
  `impression_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pubId` int(11) DEFAULT NULL,
  `siteId` int(11) DEFAULT NULL,
  `advId` int(11) DEFAULT NULL,
  `campaignId` int(11) DEFAULT NULL,
  `adId` int(11) DEFAULT NULL,
  `channelId` int(11) DEFAULT NULL,
  `total_request` BIGINT DEFAULT '0',
  `total_impression` BIGINT DEFAULT '0',
  `total_bidValue` double DEFAULT '0',
  `total_click` BIGINT DEFAULT '0',
  `total_win` BIGINT DEFAULT '0',
  `total_win_bidValue` double DEFAULT '0',
  `total_csc` BIGINT DEFAULT '0',
  `demandCharges` double DEFAULT '0',
  `supplyCost` double DEFAULT '0',
  `earning` double DEFAULT '0',
  `conversion` BIGINT DEFAULT '0',
  `bidprice_to_exchange` double DEFAULT '0',
  `cpa_goal` double DEFAULT '0',
  `exchangepayout` double DEFAULT '0',
  `exchangerevenue` double DEFAULT '0',
  `networkpayout` double DEFAULT '0',
  `networkrevenue` double DEFAULT '0',
  `billedclicks` double DEFAULT '0',
  `billedcsc` double DEFAULT '0',
  KEY `_impression_time` (`impression_time`),
  KEY `channel_hourly_pubId` (`pubId`),
  KEY `channel_hourly_siteId` (`siteId`),
  KEY `channel_hourly_adId` (`adId`),
  KEY `channel_hourly_campaignId` (`campaignId`),
  KEY `channel_hourly_advId` (`advId`),
  KEY `channel_hourly_channelId` (`channelId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `channel_daily` (
  `processing_time` datetime DEFAULT NULL,
  `impression_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pubId` int(11) DEFAULT NULL,
  `siteId` int(11) DEFAULT NULL,
  `advId` int(11) DEFAULT NULL,
  `campaignId` int(11) DEFAULT NULL,
  `adId` int(11) DEFAULT NULL,
  `channelId` int(11) DEFAULT NULL,
  `total_request` BIGINT DEFAULT '0',
  `total_impression` BIGINT DEFAULT '0',
  `total_bidValue` double DEFAULT '0',
  `total_click` BIGINT DEFAULT '0',
  `total_win` BIGINT DEFAULT '0',
  `total_win_bidValue` double DEFAULT '0',
  `total_csc` BIGINT DEFAULT '0',
  `demandCharges` double DEFAULT '0',
  `supplyCost` double DEFAULT '0',
  `earning` double DEFAULT '0',
  `conversion` BIGINT DEFAULT '0',
  `bidprice_to_exchange` double DEFAULT '0',
  `cpa_goal` double DEFAULT '0',
  `exchangepayout` double DEFAULT '0',
  `exchangerevenue` double DEFAULT '0',
  `networkpayout` double DEFAULT '0',
  `networkrevenue` double DEFAULT '0',
  `billedclicks` double DEFAULT '0',
  `billedcsc` double DEFAULT '0',
  KEY `_impression_time` (`impression_time`),
  KEY `channel_daily_pubId` (`pubId`),
  KEY `channel_daily_siteId` (`siteId`),
  KEY `channel_daily_adId` (`adId`),
  KEY `channel_daily_campaignId` (`campaignId`),
  KEY `channel_daily_advId` (`advId`),
  KEY `channel_daily_channelId` (`channelId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `channel_monthly` (
  `processing_time` datetime DEFAULT NULL,
  `impression_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pubId` int(11) DEFAULT NULL,
  `siteId` int(11) DEFAULT NULL,
  `advId` int(11) DEFAULT NULL,
  `campaignId` int(11) DEFAULT NULL,
  `adId` int(11) DEFAULT NULL,
  `channelId` int(11) DEFAULT NULL,
  `total_request` BIGINT DEFAULT '0',
  `total_impression` BIGINT DEFAULT '0',
  `total_bidValue` double DEFAULT '0',
  `total_click` BIGINT DEFAULT '0',
  `total_win` BIGINT DEFAULT '0',
  `total_win_bidValue` double DEFAULT '0',
  `total_csc` BIGINT DEFAULT '0',
  `demandCharges` double DEFAULT '0',
  `supplyCost` double DEFAULT '0',
  `earning` double DEFAULT '0',
  `conversion` BIGINT DEFAULT '0',
  `bidprice_to_exchange` double DEFAULT '0',
  `cpa_goal` double DEFAULT '0',
  `exchangepayout` double DEFAULT '0',
  `exchangerevenue` double DEFAULT '0',
  `networkpayout` double DEFAULT '0',
  `networkrevenue` double DEFAULT '0',
  `billedclicks` double DEFAULT '0',
  `billedcsc` double DEFAULT '0',
  KEY `_impression_time` (`impression_time`),
  KEY `channel_monthly_pubId` (`pubId`),
  KEY `channel_monthly_siteId` (`siteId`),
  KEY `channel_monthly_adId` (`adId`),
  KEY `channel_monthly_campaignId` (`campaignId`),
  KEY `channel_monthly_advId` (`advId`),
  KEY `channel_monthly_channelId` (`channelId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
