INSERT INTO isp_mappings (country_name, isp_ui_name, isp_name) VALUES
('Argentina','RIM','Research In Motion'),
('Asia/Pacific Region','RIM','Research In Motion'),
('Bahamas','RIM','Research In Motion'),
('Canada','RIM','Research In Motion'),
('Europe','Opera','Opera Software ASA'),
('Germany','Opera','Opera Software ASA'),
('Iceland','Opera','Opera Software ASA'),
('Indonesia','RIM','Research In Motion'),
('Mexico','RIM','Research In Motion'),
('Norway','Opera','Opera Software ASA'),
('Satellite Provider','Opera','Opera Software ASA'),
('South Africa','VDC','Assign to the Vodacom Wimax BU'),
('South Africa','CellC','Cell C'),
('South Africa','CellC','Cell C (Pty) Ltd'),
('South Africa','CellC','Cell C (Pty) Ltd.'),
('South Africa','CellC','CELL-C'),
('South Africa','CellC','Cell-C (Pty) Ltd'),
('South Africa','CellC','Cell-C Corporate'),
('South Africa','CellC','CellCSP'),
('South Africa','MTN Business','MTN Business'),
('South Africa','MTN Business','MTN Business Solutions'),
('South Africa','MTN Business','MTN Business Solutions (Pty) Ltd'),
('South Africa','MTN','Mobile Telephone Network'),
('South Africa','MTN','MTN Network Solutions'),
('South Africa','MTN','MTN Network Solutions (Pty) Ltd.'),
('South Africa','MTN','MTN Network Solutions Pty Ltd'),
('South Africa','MTN','MTN SA'),
('South Africa','MTN','MTNSD / CANARTEL'),
('South Africa','RIM','Research In Motion UK Limited'),
('South Africa','8ta or Telkom','Telkom'),
('South Africa','8ta or Telkom','Telkom SA Limited'),
('South Africa','8ta or Telkom','Telkom SA Ltd'),
('South Africa','VDC','Vodac'),
('South Africa','VDC','Vodacom'),
('South Africa','VDC','Vodacom (Pty) Ltd'),
('South Africa','VDC','Vodacom (Pty) Ltd.'),
('South Africa','VDC','Vodacom ISP Networks'),
('South Africa','VDC','Vodacom Lesotho'),
('South Africa','VDC','Vodacom Lesotho (Pty) Ltd'),
('South Africa','VDC','Vodacom PTY Ltd'),
('South Africa','VDC','Vodacom Tanzania'),
('South Africa','VDC','Vodacom-VB'),
('South Africa','VDC','Vodacom:196.207.39.247'),
('South Africa','VDC','Vodacom:IPRange:PtaGateway'),
('South Africa','VDC','Vodafone Deutschland GmbH'),
('Turkey','RIM','Research In Motion UK Limited'),
('United Arab Emirates','RIM','Research In Motion UK Limited'),
('United Kingdom','Opera','Opera Software ASA'),
('United Kingdom','RIM','Research In Motion'),
('United Kingdom','RIM','Research In Motion UK Limited'),
('United States','AT&T','AT&T Global Network Services'),
('United States','AT&T','AT&T Internet Services'),
('United States','AT&T','AT&T Mobility LLC'),
('United States','AT&T','AT&T Services'),
('United States','AT&T','AT&T U-verse'),
('United States','AT&T','AT&T Wireless'),
('United States','Opera','Opera Software ASA'),
('United States','RIM','RESEARCH IN MOTION'),
('South Africa','CellC','cellc'),
('South Africa','MTN','mtns'),
('Argentina','Claro','claro_ar'),
('Argentina','Movistar','movistar_ar'),
('Argentina','Personal','personal_ar'),
('Austria','A1','a1'),
('Austria','Hutchison 3G','hutchison 3g austria'),
('Austria','Orange','orange_at'),
('Austria','Tele Ring','tele.ring'),
('Colombia','Colombia Telecoms','colombia telecomunicaciones s.a.'),
('Colombia','Comcel','comcel'),
('Colombia','Edatel','edatel'),
('Colombia','Movistar','movistar_co'),
('Colombia','Tigo','tigo_co'),
('Ecuador','Alegro','alegro'),
('Ecuador','Movistar','moviestar'),
('Ecuador','Porta','porta'),
('France','Bouygues','bouygues telecom fr'),
('France','Cegetel','cegetel'),
('France','Digicel','digicel_fr'),
('France','Free Lliad','free_lliad'),
('France','Mobile Broadband','mobile_broadband_fr'),
('France','Orange','orange france'),
('France','SFR','s.f.r.'),
('France','Tiscali','tiscali_fr'),
('Mexico','Iusacell','iusacell / unefon'),
('Mexico','Movistar','movistar_mx'),
('Mexico','Nextel','nextel_mx'),
('Mexico','Telcel','telcel'),
('Peru','Claro','claro_pe'),
('Peru','Movistar','movistar_pe'),
('Italy','3 Italia','3 italia'),
('Italy','Wind','wind_it'),
('Italy','Tim','tim_it'),
('Italy','Vodafone','vodafone_it'),
('Italy','Hutchinson 3G','h3g_it'),
('South Africa','CellC','CellC:127.0.0.1'),
('South Africa','8ta or Telkom','Telkom Internet'),
('South Africa','8ta or Telkom','telkom mobile / 8.ta'),
('South Africa','8ta or Telkom','Telkom-Internet'),
('South Africa','VDC','Vodacom Mozambique'),
('Mexico','Telcel','vserv_telcel'),
('India','Aircel','Aircel gprs customer'),
('India','Aircel','Aircel gprs customer Delhi'),
('India','Aircel','Aircel gprs customer-North Region'),
('India','Aircel','Aircel gprs customer-South region'),
('India','Aircel','Aircel Ltd.'),
('India','Airtel','Airtel'),
('India','Airtel','Airtel Broadband'),
('India','Airtel','AIRTEL BROADBAND AND TELEPHONE SERVICES, KARNATAKA'),
('India','Alliance','Alliance Broadband Services Pvt. Ltd.'),
('India','Alliance','Alliance Broadband Services Pvt. Ltd.,Alliance Gat'),
('India','Alliance','Alliance IT Consulting (P)'),
('India','Airtel','BHARTI Airtel'),
('India','Airtel','Bharti Airtel Limited'),
('India','Idea','Idea Cellular'),
('India','Idea','Idea Cellular limited'),
('India','Reliance','Reliance Communication Limited'),
('India','Reliance','RELIANCE COMMUNICATIONS'),
('India','Reliance','Reliance Communications Ltd.DAKC MUMBAI'),
('India','Reliance','Reliance Industries Internet IP Pool'),
('India','Reliance','Reliance Jio INFOCOMM'),
('India','Vodafone','Vodacom Congo'),
('India','Vodafone','Vodafone Essar Limited'),
('India','Vodafone','Vodafone Essar Limited GPRS service'),
('India','Vodafone','Vodafone Essar Ltd., Telecommunication - Value Add'),
('India','Vodafone','Vodafone India'),
('Ghana','Vodafone','vodafone_gh'),
('Ghana','Zain','zain_gh'),
('Ghana','Tigo','tigo_gh'),
('India','Docomo','docomo'),
('India','Uninor','uninor'),
('India','Vodafone','vodafone'),
('India','Datacom','datacom'),
('India','Sistema Shyam','sistema shyam'),
('India','Reliance','reliance'),
('India','Bsnl','bsnl'),
('India','Idea','idea'),
('India','Spice','spice'),
('India','Mtnl','mtnl'),
('India','Bpl','bpl'),
('India','Tata_cdma','tata_cdma'),
('India','Virgin','virgin'),
('India','Idea_web','idea_web'),
('India','Vodafone_live','vodafone_live'),
('India','Reliance_web','reliance_web'),
('Kenya','Safaricom','safaricom'),
('Kenya','Yu','yu'),
('Kenya','Zain','zain_ke'),
('Malaysia','Digi','digi'),
('Malaysia','Maxis','maxis'),
('Malaysia','Celcom','celcom'),
('Malaysia','U Mobile','u mobile'),
('South Africa','Tertiary Education Network','tertiary education network'),
('South Africa','Megaweb','megaweb'),
('South Africa','Wireless Business Solutions','wireless business solutions'),
('South Africa','Neotel','neotel'),
('South Africa','Global Internet Access','global internet access'),
('South Africa','Verizon ZA','verizon_za'),
('South Africa','UUNET Africa - Botswana','uunet africa - botswana'),
('South Africa','Dimension Data','dimension data'),
('South Africa','Uninet Communications','uninet communications'),
('South Africa','Adept Internet (pty) Ltd','adept internet (pty) ltd'),
('South Africa','The Internet Solution','the internet solution'),
('South Africa','Imperial Online - The Imperial Connection','imperial online - the imperial connection'),
('South Africa','First Rand Bank','first rand bank'),
('South Africa','Verizon','verizon'),
('Thailand','Dtac','dtac'),
('Thailand','Truemove','truemove'),
('Thailand','Hutch','hutch_th'),
('Thailand','Ais','ais'),
('Zimbabwe','Econet','econet'),
('Nigeria','MTN','MTN Nigeria'),
('Nigeria','EMTS','EMTS Limited / Etisalat Nigeria'),
('Nigeria','Globacom','Globacom Ltd'),
('Nigeria','EMTS','vserv_etisalat_ng'),
('Nigeria','Airtel','Airtel Networks Limited'),
('Russian Federation','MegaFon','megafon'),
('Russian Federation','MegaFon','OJSC MegaFon'),
('Kenya','Safaricom','Safaricom'),
('Kenya','Safaricom','Safaricom Limited'),
('India','Reliance','Reliance Communications'),
('India','Bsnl','National Internet Backbone'),
('India','Docomo','Ttsl-isp Division'),
('India','Docomo','Tata Teleservices (Maharashtra) Ltd'),
('India','Bpl','Loop Mobile'),
('India','Sistema Shyam','Shyam Internet Services Pvt Ltd'),
('India','Sistema Shyam','MTS'),
('India','Sistema Shyam','SHYAM Internet service provider in India.'),
('India','Aircel','Aircel'),
('India','Vodafone','Vodafone IN'),
('India','Airtel','Airtel Hotspot Cafe Coffe'),
('India','Docomo','Tata Teleservices ISP'),
('India','Reliance','Reliance'),
('India','Spice','Quadrant Televentures Limited'),
('India','Docomo','Tata Mobile'),
('India','Airtel','Bharti Broadband'),
('India','Mtnl','Mtnl Internet Service Provider In The City Of Delh'),
('India','Mtnl','Mahanagar Telephone Nigam Ltd.'),
('India','Docomo','Tata Teleservices Limited'),
('India','Spice','Sify Limited'),
('India','Airtel','Airtel Broadband & Telephone Services-kolkatta'),
('India','Aircel','aircel'),
('India','Docomo','TATA Communications'),
('India','Idea','Idea'),
('India','Aircel','Dishnet Wireless Limited'),
('India','Uninor','D-VoiS Broadband Private Limited'),
('India','Airtel','Airtel Networks Kenya Ltd'),
('India','Mtnl','Mahanagar Telephone Nigam Ltd. ISP Division, New D'),
('India','Docomo','Tata Teleservices Maharashtra Ltd'),
('India','Docomo','TATA DOCOMO'),
('India','Airtel','Airtel Broadband And Telephone Services Karnataka'),
('India','Airtel','airtel'),
('India','Idea','Idea Cellular Ltd'),
('India','Uninor','Uninor'),
('India','Docomo','Tata Indicom'),
('India','Bsnl','Bharat Sanchar Nigam Ltd'),
('India','Airtel','Airtel limited'),
('India','Uninor','Videocon'),
('India','Vodafone','Cable & Wireless UK P.U.C.'),
('India','Aircel','AIRCEL'),
('India','Mtnl','Mahanagar Telephone Nigam Ltd., ISP Division, New'),
('India','Airtel','Airtel Broadband And Telephone Services, Karnataka'),
('India','Uninor','TATA Communications Internet Services Ltd'),
('India','Airtel','Bhartitelesonic Is A Leading Telecoms Provider'),
('India','Sistema Shyam','Shyam Internet Services Ltd'),
('Thailand','Hutch','Ministry of Infomation Communication Technology'),
('Thailand','Ais','CS LoxInfo'),
('Thailand','Ais','C/o Cs Loxinfo Public Company Limited'),
('Thailand','Truemove','True Internet'),
('Thailand','Hutch','CAT Telecom Public Company Limited'),
('Thailand','Hutch','Communication Authority of Thailand, CAT'),
('Thailand','Truemove','True Move Company Limited'),
('Thailand','Hutch','CAT Telecom public company Ltd'),
('Thailand','Truemove','truemove H 4G LTE'),
('Thailand','Dtac','DTAC TriNet Co.,Ltd.'),
('Thailand','Dtac','Internet Thailand Company Limited'),
('Thailand','Truemove','Truemove'),
('Thailand','Dtac','Total Access Communication PLC'),
('Thailand','Ais','AIS Mobile'),
('Thailand','Ais','Loxley Information Company Ltd.'),
('Thailand','Ais','CS LOXINFO Public Company Limited.'),
('Nigeria','MTN','MTN NIGERIA Communication limited'),
('Nigeria','MTN','MTN'),
('Nigeria','Zain','zain'),
('Nigeria','Airtel','Airtel'),
('Nigeria','Airtel','Airtel Networks Nigeria Ltd'),
('Nigeria','Zain','Celtel Nigeria Limited t.a ZAIN'),
('Nigeria','Etisalat','Etisalat'),
('Nigeria','Glo','Glo'),
('Nigeria','Etisalat','etisalat_ng'),
('Nigeria','M-Tel','M-Tel'),
('Nigeria','Vodafone','Vodafone'),
('Nigeria','MTN','mtn_ng'),
('Ghana','Expresso','Expresso Telecom Ltd'),
('Ghana','Tigo','tiGO'),
('Ghana','Airtel','Airtel'),
('Ghana','Mtn','Scancom Ltd'),
('Ghana','Vodafone','Ghana Telecom'),
('Ghana','Airtel','Bharti Airtel (Ghana) Limited'),
('Ghana','Expresso','Expresso'),
('Ghana','Tigo','Millicom Ghana Limited'),
('Ghana','Mtn','mtn_gh'),
('Ghana','Glo Mobile','Glo Mobile Ghana Ltd'),
('Ghana','Zain','Zain Communications Ltd'),
('Ghana','Vodafone','Vodafone'),
('Ghana','Vodafone','Vodafone Ghana'),
('Spain','movistar_es','movistar'),
('Spain','movistar_es','Grupalia Internet S.A.'),
('Spain','movistar_es','Blend Telecom S.L.'),
('Spain','movistar_es','movistar_es'),
('Spain','movistar_es','Prisco Electronica S.L.'),
('Spain','bt_es','bt_es'),
('Spain','movistar_es','Corporacio Megatel S.L.'),
('Spain','movistar_es','Maxen Technologies S.l.'),
('Spain','vodafone_es','Vodafone Spain'),
('Spain','vodafone_es','vodafone_es'),
('Spain','movistar_es','Jazz Telecom S.A.'),
('Spain','movistar_es','OGIC Informatica S.L.'),
('Spain','ono','ono'),
('Spain','movistar_es','Skylogic Espana S.A.'),
('Spain','ono','ONO'),
('Spain','mobile_broadband_es','Procono S.A.'),
('Spain','euskaltel','euskaltel'),
('Spain','telefonica_de_espana','Telefonica de Espana'),
('Spain','euskaltel','Euskaltel'),
('Spain','movistar_es','Xtra Telecom S.A.'),
('Spain','movistar_es','Embou Nuevas Tecnologias'),
('Spain','movistar_es','Buho Real TV S.L.U.'),
('Spain','euskaltel','Euskaltel S.A.'),
('Spain','yoigo','yoigo'),
('Spain','orange_es','orange_es'),
('Spain','orange_es','Orange'),
('Spain','movistar_es','Innovaciones Tecnlogicas del Sur S.L.'),
('Spain','bt_es','BT'),
('Spain','movistar_es','Red digital de telecomunicaciones de las islas bal'),
('Spain','yoigo','XFERA Moviles S.A.'),
('Spain','movistar_es','Orange Catalunya Xarxes de Telecomunicacions S.A.'),
('Spain','movistar_es','ServiHosting Networks S.L.'),
('Spain','vodafone_es','Vodafone'),
('Spain','movistar_es','Onlycable Comunicaciones S.l.'),
('Spain','movistar_es','Tele Alhama S.l'),
('Spain','orange_es','Orange Espana'),
('Spain','telefonica_de_espana','telefonica_de_espana'),
('Spain','movistar_es','Telewifi S.l.'),
('Spain','tme','TME'),
('Spain','yoigo','Yoigo'),
('Spain','movistar_es','Lorca TV Sol S.L.'),
('Spain','mobile_broadband_es','mobile_broadband_es'),
('Spain','movistar_es','Iberbanda S.A.'),
('Spain','movistar_es','Globe Operator Telecom Sl'),
('Spain','movistar_es','Universidad del Pais Vasco / Euskal Herriko Uniber'),
('Spain','movistar_es','Orange Web Services S.L.'),
('Spain','tme','tme'),
('Australia',' Daniel Lawrence','Keogh'),
('Australia',' C/- Macquarie University','Dunmore Lang College'),
('Australia',' Your Internet Connection','Netro'),
('Australia',' Tower 2','8/F'),
('Australia',' Mount Waverley','Level 3 501 Blackburn Road'),
('Australia',' Canberra ACT','Tuggeranong Office Park'),
('Australia',' Sydney','IPC Network Services'),
('Australia',' PAUL JAMES T/A GoDedicated','TYQUIN'),
('Australia','optus','Optus'),
('Australia',' Dedicated and Virtual Server','AUSWEB - Web Hosting'),
('Australia',' Fisheries & Forestry (Q','Department of Agriculture'),
('Australia',' Level 9','Suite 2'),
('Australia',' Web Hosting Provider','Ingenuity Hosting Pty Ltd'),
('Australia',' Pty. Ltd','abm Australasia'),
('Australia',' LLC','IO Capital Princess'),
('Australia',' North Sydney','NextGen.Net Pty Ltd'),
('Australia',' The Land Division of Property Ser','Landcom Pty Ltd'),
('Australia',' Perth','45RU Pty Ltd. Internet Service Provider'),
('Australia',' Web Hosting','Telligence'),
('Australia',' 155 Castlereagh St','Level 13'),
('Australia',' ISP','Community Assets Ltd'),
('Australia',' Alan Robert T/a Radcomp Computers','Pearson'),
('Australia',' Virtual and Dedicated server coloca','Web24 Pty Ltd'),
('Australia',' LLC','Xponent'),
('Australia',' GBE','Norfolk Telecom'),
('Australia',' Australia','Telarus Pty Ltd. xDSL Provider'),
('Australia',' Employment and Workplace','Department of Education'),
('Australia',' LLC','Choopa'),
('Australia',' a business unit of Pacific Mobile Communica','Tiare'),
('Australia',' Australia.','Capital Networks'),
('Australia',' City Broadband Service','SHTECH'),
('Australia',' Inc.','Take Two Interactive Software'),
('Australia',' 433 Logan Rd','Suite 4.25'),
('Australia','telstra','Telstra Internet'),
('Australia',' Australia','GCOMM Pty Ltd Internet Service Provider'),
('Australia',' Exchange Plaza','Level 23'),
('Australia',' Australian Centre for Advanced Computing and','ac3'),
('Australia',' Financial Services','Liberty Financial Pty Ltd'),
('Australia',' LLC','MavenWire'),
('Australia',' Penrith Ltd.','St. Pauls Grammar School'),
('Australia',' ASP for remote access services','Citrix Online'),
('Australia',' 100 arthur Street','Level 15'),
('Australia',' Australia - Callaghan cam','University of Newcastle'),
('Australia','hi3g','Vodafone Australia'),
('Australia',' Queensland','Brisbane'),
('Australia',' trading as ISPNet','ISP Networks Pty Ltd'),
('Australia',' Systems Integrator','NetCraft Australia Pty Ltd'),
('Australia',' Workplace Relations','Department of Employment'),
('Australia',' Western Australia','Perth'),
('Australia',' ACT','Australian Sports Commission. Bruce'),
('Australia',' Governor Phillip Tower','Level 23'),
('Australia',' NSW','TNT Australia'),
('Australia',' Attorney-General\'s Department','CERT Australia'),
('Australia',' Victorian Government','Department of Infrastructure'),
('Australia',' Managed Hosting Solutions','Zone Networks Pty Ltd'),
('Australia',' Web Hosting Provider','Conetix'),
('Australia',' Monitoring','ISP Services'),
('Australia',' Australian','Sema Operations Pty Limited'),
('Australia','optus','OCPL'),
('Australia',' Manufacturer','Sharp Corporation of Australia'),
('Australia',' 88 Creek St','Level 4'),
('Australia',' Launceston','St Patricks College'),
('Australia',' Multi Peered Internet and Data','Multi Homed'),
('Australia',' Pty Ltd.','PerthWeb'),
('Australia',' Hosting Provider','OzServers'),
('Australia',' Application Hosting','YourASP Pty Ltd'),
('Australia',' A subsidiary of Netwide','REA Group'),
('Australia',' AMP Place','Level 24'),
('Australia',' Damien Geoffrey','Gardner'),
('Australia',' Converged Network Service Provider','IP Systems'),
('Australia','soul','TPG Internet'),
('Australia',' Data Centres','Digital Sense'),
('Australia',' Wireless Carrier','Etherwave'),
('Australia',' Service Provider Australia','Seccom Networks'),
('Australia',' Building C','Level 2'),
('Australia',' NSW.','Voice over IP Provider'),
('Australia',' BNE3 Datacentre','WebCentral PtyLtd'),
('Australia',' LLC','Zero 2 Infinity'),
('Australia',' Broadband Internet Prov','Wideband Networks Pty Ltd'),
('Australia',' Carrier Service Pr','Digital Distribution Australia'),
('Australia',' Colo & ISP Provider','SISGroup'),
('Australia',' Sydney','University of Technology'),
('Australia',' Satellite Broadband Provider','IPSTAR Australia'),
('Australia',' Mission Critical Cloud','Bulletproof'),
('Australia',' Sydney','Catholic Education Office'),
('Australia',' LLC.','DigitalFyre Internet Solutions'),
('Australia',' Broadband Networks and Internet','Vertical Telecoms'),
('Australia',' Melbourne and Brisbane','IX for Sydney'),
('Australia',' IP Solutions Provider','United IP'),
('Australia',' 100 Harris St','Level 5'),
('Australia',' Managed Services Pr','Conexim Australia Pty Limited'),
('Australia',' LLC','Moomu'),
('Australia',' LLC','Cloudflare Sydney'),
('Australia',' Sydney Datacentre','WebCentral PtyLtd'),
('Australia',' Melbourne','The University of Melbourne'),
('Australia',' C/- Macquarie University','Robert Menzies College'),
('Australia',' Financial Services','Greater Building Society'),
('Australia',' Adrian Alexander','Sender'),
('Australia',' LLC','Adhost Internet Advertising'),
('Italy','tim_it','Clouditalia Telecomunicazioni S.p.A.'),
('Italy','3 italia','Infracom Italia S.p.A.'),
('Italy',' Sviluppo e Studi Superiori in Sard','Centro Ricerca'),
('Italy',' Societa Cooperativa','Consorzio Elettrico Di Storo'),
('Italy','wind_it','Italia Online SpA'),
('Italy','wind_it','OVH SAS'),
('Italy','tim_it','Qcom spa'),
('Italy','vodafone_it','Vodafone Italia DSL'),
('Italy','tim_it','Terrecablate Reti e Servizi S.R.L.'),
('Italy','tim_it','Fastweb'),
('Italy','3 italia','Telecom Italia'),
('Italy','tim_it','Verizon Italia SpA'),
('Italy',' Italy','I.N.P.S. national network'),
('Italy','wind_it','Infostrada'),
('Italy','wind_it','Wind Telecomunicazioni'),
('Italy','vodafone_it','Vodafone Omnitel B.V.'),
('Italy',' LLC','Bit Trade'),
('Italy','3 italia','H3G Italy'),
('Italy','wind_it','Wind Telecomunicazioni SpA'),
('Italy','vodafone_it','Vodafone Omnitel N.v.'),
('Italy','tim_it','NGI SpA'),
('Italy','tim_it','Telecom Italia Mobile'),
('Mexico',' SA de CV','Tecnologia Uno-Cero'),
('Mexico',' S.A. de C.V.','Alta Tecnologia Precitool'),
('Mexico',' S.A. de C.V.','Casa de Bolsa Arka'),
('Mexico',' S.A. de C.V.','Rey de Occidente'),
('Mexico',' S.A. de C.V.','Ternium Mexico'),
('Mexico',' S.A. de C.V','Intertec de Mexico'),
('Mexico',' S.A. de C.V.','Sistemas Aplicados de la C.P.'),
('Mexico',' S.A. de C.V.','Computel del Norte'),
('Mexico',' S.A. de C.V.','Logical'),
('Mexico',' S.A. de C.V.','GRUPO ICA'),
('Mexico',' S','Aeropuerto Internacional de la Ciudad de Mexico'),
('Mexico',' S.A. de C.V.','Cablevision de Saltillo'),
('Mexico',' A.C.','Universidad Iberoamericana'),
('Mexico',' S.A de C.V.','Televisa'),
('Mexico',' S.A.B. de C.V.','Axtel'),
('Mexico',' S. de R.L. de C.V.','Microenlace de Mexico'),
('Mexico',' S.A.B. de C.V.','Grupo Radio Centro'),
('Mexico',' A.C.','Centros Culturales de Mexico'),
('Mexico',' S.A. de C.V.','Versus Systems'),
('Mexico',' S.A. de C.V.','Cable Administradora'),
('Mexico',' S.C.','Fraser Fisher y Asociados'),
('Mexico',' S.A. de C.V.','Starsatel'),
('Mexico',' S.A. de C.V','Infolink'),
('Mexico',' S.A. de C.V.','Macrotec Computacion'),
('Mexico',' S.A. de C.V.','Cydsa Corporativo'),
('Mexico',' Inst. de Banca Multiple','Banco Monex S.A.'),
('Mexico',' S.A. de C.V.','Valores Finamex'),
('Mexico',' S. A. de C. V.','Omninet'),
('Mexico',' S.A. de C.V.','Softtek Servicios Corporativos'),
('Mexico',' S.A. de C.V.','Casa de Bolsa Banorte'),
('Mexico',' S. De R.l. De C.','Creative Multilingual Strategies'),
('Mexico',' S.A. de C.V.','Terra Networks Mexico'),
('Mexico',' S.A. de C.V.','Bajanet Comunicaciones'),
('Mexico',' S.A. de C.V.','Electronica Steren'),
('Mexico',' S.A. de C.V.','IP Matrix'),
('Mexico',' S.A. de C.V.','Imatech Networks'),
('Mexico',' S.A. de C.V.','CablevisiÃ¯Â¿Â½n'),
('Mexico',' S.A.B. de C.V.','Maxcom Telecomunicaciones'),
('Mexico',' S.A.B. de C.V.','Grupo Bimbo'),
('Mexico',' S.A. de C.V.','Television Internacional'),
('Mexico',' S.A. de C.V.','Micronet de Mexico'),
('Mexico',' S.A. de C.V.','Internet Comunicacion'),
('Mexico',' S.A. de C.V.','Volkswagen de Mexico'),
('Mexico',' S.A. de C.V.','Serviware'),
('Mexico',' S.A. De C.V.','Pharmacia De Mexico'),
('Mexico',' S.A. de C.V.','Infonet del Bajio'),
('Mexico',' S.A. de C.V.','Protel I-Next'),
('Mexico',' S.A. de C.V.','Telefonos del Noroeste'),
('Mexico',' Centro de Excelencia Empresarial','Integer'),
('Mexico',' Value Grupo Fina','Value S.A. de C.V. Casa de Bolsa'),
('Mexico',' S.A. de C.V.','Neoris de MÃ¯Â¿Â½xico'),
('Mexico',' SA','Hojalata y Lamina'),
('Mexico',' S.A. de C.V.','Kmart Mexico'),
('Mexico','iusacell / unefon','Iusacell'),
('Mexico',' S.A. de C.V.','Operadora de Rastreos UDA'),
('Mexico',' S.A. de C.V.','Abastecedora de Conectividad'),
('Mexico',' S.A. de C.V.','Gigacable de Aguascalientes'),
('Mexico',' Casa De Bolsa','Anahuac'),
('Mexico',' S.A. de C.V.','Cemex Mexico'),
('Mexico',' Optica y Electr','Instituto Nacional de Astrofisica'),
('Mexico',' S.A. de C.V.','Creatividad Internet Enlaces'),
('Mexico',' S.A. de C.V.','Tiendas Comercial Mexicana'),
('Mexico',' S.A.','Banca Afirme'),
('Mexico',' S. A.','Electronica y Comunicaciones'),
('Mexico',' S. De Rl De C.v.','Multiservice Strategies'),
('Mexico',' S.A. de C.V.','Bolsa Mexicana de Valores'),
('Mexico',' A. C.','Colegio Morelos de Cuernavaca'),
('Mexico',' A.c.','Iteso'),
('Mexico',' A.c.','Imit'),
('Mexico',' S.A. de C.V.','TV Azteca'),
('Mexico',' S.A. De C.v.','Agi Mexicana'),
('Mexico',' S y T de Veracruz','Camara Nacional de Comercio'),
('Mexico',' AC','Universidad La Salle'),
('Mexico',' S.A. de C.V.','Mega Cable'),
('Mexico',' S.A. de C.V.','Grupo Copyanet'),
('Mexico','telcel','Telmex'),
('Mexico',' S.A. de C.V.','El Chorro'),
('Mexico',' S.A. de C.V','Grupo de Telecomunicaciones Mexicanas'),
('Mexico',' S.A. de C.V.','Internet Engine'),
('Mexico',' S.A.','Vshc'),
('Mexico',' S.A. de C.V.','Expansion'),
('Mexico',' S.A. de C.V.','Servnet Mexico'),
('Mexico',' S.A. de C.V.','Cable y Comunicacion de Campeche'),
('Mexico',' S.A. DE C.V','Pioneer Speakers'),
('Mexico',' S.A. de C.V.','Informatica XXI'),
('Mexico',' S.A. De C.v.','Manpower'),
('Mexico',' S.A. de C.V.','Teleinformacion'),
('Mexico',' S.A. de C.V.','Aspel de MÃ¯Â¿Â½xico'),
('Mexico',' LC','DataShack'),
('Mexico',' S.C.','Mexico Communicates'),
('Mexico',' S.A. de C.V.','Sait'),
('Mexico',' S.A.','Banco Nacional de Mexico'),
('Mexico',' S.A. de C.V.','Inter Red Toluca'),
('Mexico',' S.C.','Escuela Bancaria y Comercial'),
('Mexico',' S. de R.L. de C.V.','Home Depot Mexico'),
('Mexico',' S.A. de C.V.','Servicios Electronicos Globales'),
('Mexico',' S. de R.L. de C.V.','Konecta de Mexico'),
('Mexico',' S.A. de C.V.','Operbes'),
('Mexico',' S.A. de C.V.','MVS Net'),
('Mexico',' S.A. de C.V.','Global PCNet'),
('Mexico',' S.A. de C.V.','Arnecom'),
('Mexico',' A.C.','Universidad Regiomontana'),
('Mexico',' S. de R.L. de C.V.','Metro Net Hosting'),
('Mexico',' S.A. de C.V.','Banca Mexicana de Valores'),
('Mexico',' S.A de C.V.','Enlaces Digitales del Golfo'),
('Mexico',' SA de CV','NEMAK'),
('Mexico',' S.A.','HSBC Mexico'),
('Mexico',' S.A. de C.V.','Bufete Consultor deMexico'),
('Mexico',' S.A. de C.V.','Sixsigma Networks Mexico'),
('Mexico',' S. A. de C.V.','Comunicacion en informacion'),
('Mexico',' S.A. de C.V.','TV Rey de Occidente'),
('Mexico',' S. de R.L. de C.V.','Alestra'),
('Mexico',' S.A. de C.V.','Caribe Net'),
('Mexico',' S.c.','Universidad Latinoamericana'),
('Mexico',' S.A. de C.V.','Megacable Comunicaciones de Mexico'),
('Mexico',' S.A. de C.V.','Grupo Corporativo ITS'),
('Mexico',' S.A. de C.V.','RepCom de Mexico'),
('Mexico',' S.A. de C.V.','BT Latam Mexico'),
('Mexico',' A.C.','El Colegio de Mexico'),
('Mexico',' S.A. de C.V.','Internet OnLine'),
('Mexico',' S.A. de C.V.','WL Comunicaciones'),
('Mexico',' S.c.p.','Factor Finvex'),
('Mexico','iusacell / unefon','Level 3 Communications'),
('Mexico',' S.A.P.I. de C.V.','G TEL Comunicacion'),
('Mexico',' S.A. de C.V.','Pixel Internacional'),
('Mexico',' S.A. De C.v.','Acciones Y Valores Banamex'),
('Mexico',' S.A. de C.V.','Marcatel Com'),
('Mexico',' S.A. de C.V.','RadioMovil Dipsa'),
('Mexico',' A.C.','Centro Internacional de Negocios Monterrey'),
('Mexico',' S. de R.L. de C.','Mexico Red de Telecomunicaciones'),
('Mexico',' A.C.','Centro de Investigaciones en Optica'),
('Mexico',' SA de CV','Vector Casa de Bolsa'),
('Mexico',' S.C.','Escuela Camara de Comercio'),
('Mexico',' S. de R.L. de C.V.','Konecta'),
('Mexico',' S.A. de C.V.','Mabe'),
('Mexico',' S.A. de C.V.','Tele Cable Centro Occidente'),
('Mexico',' S. de R.L. de C.V.','Centris de Mexico'),
('Mexico',' S.A. de C.V.','Cromasoft'),
('Mexico',' S.A.P.I. de C.V.','Metro Net'),
('Mexico',' S.A.','Banco Interacciones'),
('Mexico',' S. de R.L. de C.V.','Enlaces Integra'),
('Mexico',' S.C.','NIC MÃ¯Â¿Â½xico'),
('Mexico',' S.A. de C.V.','CEMEX Central'),
('Mexico',' S.A. de C.V.','Omega Solder Mexico'),
('Mexico',' S.C.','Sociedad Educativa de las Americas'),
('Mexico',' S.A. de C.V.','Industrias Xignux'),
('Mexico',' S.A.','TV de Uruapan'),
('Mexico',' S.A. de C.V.','Miditel'),
('Mexico',' S.A. de C.V.','Wireless'),
('Mexico',' Utt A.c.','Nodo Nacional De Informacion Empresarial'),
('Mexico',' S.A. de C.V.','Logica Industrial'),
('Mexico',' S.A. de C.V.','GIGA-COM'),
('Mexico',' S.A. de C.V.','Podernet'),
('Mexico',' S.A. de C.V.','Acciones y Valores de Mexico'),
('Mexico',' Tecnologia e Informacion','Consultoria'),
('Mexico',' S.A. de C.V.','Red Five Two'),
('Mexico',' S.A.B. de C. V.','Axtel'),
('Mexico',' S.A. De C.v.','De Papel San Francisco'),
('Mexico',' Institucion de Banc','Banco Santander (Mexico) S.A.'),
('Mexico',' S.A. de C.V.','Espacios de Mexico'),
('Mexico',' S.A. de C.V.','Netra'),
('Mexico',' S.A. de C.V.','Servicios de Agua Potable'),
('Mexico',' A.C.','Universidad Autonoma de Guadalajara'),
('Mexico',' S.A. de C.V.','CVitae Nacional'),
('Mexico',' S. de R.L. de C.V.','Spectro Networks'),
('Mexico',' S.A. de C.V.','Productos Corinter'),
('Mexico',' S. A. de C.V.','Telecable del Mineral'),
('Mexico',' S.A. De C.v.','Cybernet'),
('Mexico',' S.A. de C.V.','Grupo Hidalguense de Desarrollo'),
('Mexico',' S.A. de C.V.','Triara.com'),
('Mexico',' Institucion de Ban','Banco Mercantil del Norte S.A.'),
('Mexico',' S.A. de C.V.','VPN de Mexico'),
('Mexico',' S.A. de C.V.','Servicios Administrados Mexis'),
('Mexico',' S.A. de C.V.','ComUnNet'),
('Mexico',' S.A. de C.V.','Omnilife de Mexico'),
('Mexico',' S.A. de C.V.','ASAE Consultores'),
('Jordan','Zain_jo','FIRSTNET (First Data Communication Group)'),
('Jordan','Zain_jo','zain_jo'),
('Jordan','Umniah','Umniah Mobile Company PLC'),
('Jordan','Orange','Orange'),
('Jordan','Zain_jo','Jordan Mobile Telephone Services Company Ltd'),
('Jordan','Orange','Jordan Telecommunications Company'),
('Jordan','Umniah','Jordanian Universities Network L.L.C.'),
('Jordan','Umniah','Umniah Lil-Hawatef Al-Mutanaqelah Co.'),
('Jordan','Zain_jo','Linkdotnet-Jordan'),
('Kuwait','Zain_kw','zain_kw'),
('Kuwait','Viva_kw','Viva Kuwait'),
('Kuwait','Zain_kw','Qualitynet'),
('Kuwait','Zain_kw','Mobile Telecommunications Company'),
('Kuwait','Wataniya','Wataniya'),
('Kuwait','Viva_kw','viva_kw'),
('Kuwait','Wataniya','Wataniya Telecom'),
('Kuwait','Wataniya','wataniya'),
('Malaysia','Maxis','Maxis Communications Bhd'),
('Malaysia','Maxis','Maxis'),
('Malaysia','U Mobile','Telekom Malaysia'),
('Malaysia','Maxis','Maxis 3G'),
('Malaysia','Celcom','Celcom Internet Service Provider'),
('Malaysia','Maxis','Maxis Broadband Sdn Bhd'),
('Malaysia','Digi','DiGi Telecommunications Sdn Bhd'),
('Malaysia','Maxis','TIME dotCom Berhad'),
('Malaysia','Digi','DiGi Telecommunications Sdn. Bhd.'),
('Malaysia','Maxis','Maxis Communications'),
('Malaysia','U Mobile','U Mobile Sdn Bhd'),
('United Arab Emirates','du','du'),
('United Arab Emirates','etisalat_ae','Emirates Integrated Telecommunications Company PJS'),
('United Arab Emirates','etisalat_ae','etisalat_ae'),
('United Arab Emirates','etisalat_ae','Etisalat'),
('United Arab Emirates','etisalat_ae','Emirates Telecommunications Corporation'),
('Brazil','claro_br','Claro S/A'),
('Brazil','claro_br','Virtua'),
('Brazil','vivo','Hardonline Ltda'),
('Brazil','tim_br','Global Village Telecom'),
('Brazil','oi','Oi Fixo'),
('Brazil','oi','Silva & Silveira S/c Ltda - Me'),
('Brazil','oi','Way TV Belo Horizonte S.A.'),
('Brazil','tim_br','Tim Celular S.A.'),
('Brazil','oi','Oi'),
('Brazil','vivo','vivo'),
('Brazil','ctbc celular','CTBC'),
('Brazil','oi','Oi Internet'),
('Brazil','ctbc celular','ctbc celular'),
('Brazil','oi','Oi Velox'),
('Brazil','oi','oi'),
('Brazil','telefonica_br','Vivo'),
('Brazil','telefonica_br','Telefonica Data S.A.'),
('Brazil','ctbc celular','CTBC Celular'),
('Brazil','claro_br','Century Telecom Ltda'),
('Brazil','ctbc celular','Telecom S/a'),
('Brazil','sercomtel','Internet by Sercomtel S.A.'),
('Brazil','vivo','Vivo'),
('Brazil','claro_br','Claro BR'),
('Brazil','claro_br','Embratel'),
('Colombia','Comcel','Telmex Colombia S.A.'),
('Colombia','Edatel','Edatel'),
('Colombia','Movistar','Level 3 Communications'),
('Colombia','Tigo','Tigo'),
('Colombia','Comcel','Claro Colombia'),
('Colombia','Edatel','Edatel S.A. E.s.p'),
('Colombia','Movistar','Diveo de Colombia Ltda.'),
('Colombia','Movistar','movistar'),
('Colombia','Movistar','Telefonica Moviles Colombia'),
('Colombia','Edatel','UNE'),
('Colombia','Comcel','Columbus Networks de Colombia Limitada'),
('Colombia','Colombia Telecoms','Sprint'),
('Colombia','Movistar','Colombia Telecomunicaciones S.A. Esp'),
('Colombia','Tigo','TIGO COLOMBIA'),
('Ecuador','Movistar','Otecel S.A.'),
('Ecuador','Alegro','Nacional De Telecomunicaciones - Cnt Ep'),
('Ecuador','Porta','CONECEL'),
('Ecuador','Alegro','Corporacion Nacional De Telecomunicaciones - Cnt E'),
('Ecuador','Alegro','Level 3 Communications'),
('Ecuador','Movistar','Movistar'),
('United Kingdom','orange_uk','BT'),
('United Kingdom','jt-wave','jt-wave'),
('United Kingdom','mobile_broadband_uk','Zen Internet Ltd'),
('United Kingdom','bt_uk','bt_uk'),
('United Kingdom','tiscali_uk','tiscali_uk'),
('United Kingdom','jt-wave','JT'),
('United Kingdom','mobile_broadband_uk','mobile_broadband_uk'),
('United Kingdom','truphone','T-Mobile (UK) Limited'),
('United Kingdom','cable and wireless guernsey telecom','cable and wireless guernsey telecom'),
('United Kingdom','bt_uk','BT'),
('United Kingdom','orange_uk','Orange Home UK'),
('United Kingdom','truphone','truphone'),
('United Kingdom','o2_uk','o2_uk'),
('United Kingdom','o2_uk','Sky Broadband'),
('United Kingdom','cable and wireless guernsey telecom','JT (Guernsey) Limited'),
('United Kingdom','cable and wireless guernsey telecom','Demon Internet / Thus plc'),
('United Kingdom','mobile_broadband_uk','Star Technology Services Limited'),
('United Kingdom','dobson telephone co','dobson telephone co'),
('United Kingdom','tiscali_uk','Tiscali UK Limited'),
('United Kingdom','orange_uk','Orange mobile'),
('United Kingdom','virgin_uk','virgin_uk'),
('United Kingdom','o2_uk','Be Un Limited'),
('United Kingdom','virgin_uk','Virgin Media'),
('United Kingdom','opal telecom ltd','opal telecom ltd'),
('United Kingdom','virgin_uk','Virgin Mobile UK'),
('United Kingdom','o2_uk','Telefonica O2 UK'),
('United Kingdom','gilat_satcom','gilat_satcom'),
('United Kingdom','vodafone_uk','vodafone_uk'),
('United Kingdom','hutchison 3g uk ltd','Three'),
('United Kingdom','o2_uk','O2 (UK)'),
('United Kingdom','virgin_uk','Virgin Media Business'),
('United Kingdom','orange_fr','orange_fr'),
('United Kingdom','vodafone_uk','Vodafone UK'),
('United Kingdom','cable and wireless guernsey telecom','Cable & Wireless UK P.U.C.'),
('United Kingdom','mobile_broadband_uk','Link Connect Services Ltd'),
('United Kingdom','mobile_broadband_uk','Kcom'),
('United Kingdom','hutchison 3g uk ltd','hutchison 3g uk ltd'),
('United Kingdom','cable and wireless guernsey telecom','Sure Guernsey Limited'),
('United Kingdom','tiscali_uk','TalkTalk'),
('United Kingdom','orange_uk','Orange (UK)'),
('United Kingdom','mobile_broadband_uk','Telecitygroup International Limited'),
('United Kingdom','mobile_broadband_uk','Redwing Satellite Solutions'),
('United Kingdom','orange_uk','PlusNet Technologies Ltd'),
('United Kingdom','orange_uk','orange_uk'),
('Guatemala','movistar_gt','movistar'),
('Guatemala','comcel / tigo','Comcel Guatemala S.A.'),
('Guatemala','claro_gt','claro_gt'),
('Guatemala','claro_gt','Amnet Datos Guatemala'),
('Guatemala','comcel / tigo','comcel / tigo'),
('Guatemala','movistar_gt','Telefonica Moviles Guatemala S.A.'),
('Guatemala','movistar_gt','movistar_gt'),
('Guatemala','claro_gt','Claro'),
('Guatemala','claro_gt','Columbus Networks Guatemala'),
('Guatemala','claro_gt','Telgua'),
('Uruguay','ancel','Administracion Nacional de Telecomunicaciones'),
('Uruguay','movistar_uy','Movistar'),
('Uruguay','ancel','ancel'),
('Uruguay','movistar_uy','movistar_uy'),
('Uruguay','movistar_uy','Telefonica Moviles del Uruguay SA'),
('Vietnam','mobifone','Mobifone Global JSC'),
('Vietnam','viettel mobile','Viettel Corporation'),
('Vietnam','vinaphone','vinaphone'),
('Vietnam','mobifone','The Corporation for Financing and Promoting Techno'),
('Vietnam','vietnamobile','Vietnamobile (HT Mobile )'),
('Vietnam','beeline','beeline'),
('Vietnam','beeline','Gtel Mobile Join Stock Company'),
('Vietnam','viettel mobile','Viettel Mobile'),
('Vietnam','mobifone','VTTC Co., LTD'),
('Vietnam','mobifone','Vietnam Posts and Telecommunications (VNPT)'),
('Vietnam','mobifone','mobifone'),
('Vietnam','vietnamobile','HT Mobile Communication Center'),
('Vietnam','vinaphone','Vinaphone'),
('Vietnam','mobifone','FPT Telecom'),
('Vietnam','mobifone','Vietnam Posts and Telecommunications Corp (VNPT)'),
('Vietnam','vietnamobile','vietnamobile'),
('Vietnam','mobifone','CMC Telecom Infrastructure Company'),
('Vietnam','vinaphone','VDC')
ON DUPLICATE KEY UPDATE country_name = VALUES(country_name);
