#!/bin/sh -x
#DEBHELPER#
set -e
if [ -e /etc/kritter-tern-file-pull-conf-adserving-cpm-cpm-rev-max-service/run ]; then
        update-service --remove /etc/kritter-tern-file-pull-conf-adserving-cpm-cpm-rev-max-service
fi

