#!/bin/sh

exec 2>&1

DAEMON=/usr/share/kritter/tern/tern_file_pull/bin/tern_file_pull.py
CONF=/usr/share/kritter/tern/tern_file_pull/conf/kritter/adserving_cpm_cpm_rev_max/

SLEEP=300

echo "Starting in $SLEEP seconds..."
sleep $SLEEP


exec setuidgid optimad python ${DAEMON} ${CONF}
