#!/bin/sh -x
#DEBHELPER#
set -e
if [ -d /etc/kritter-tern-dir-pull-conf-mad-handset-service/log/main ]; then
        chown -v nobody:nogroup /etc/kritter-tern-dir-pull-conf-mad-handset-service/log
        chown -v nobody:nogroup /etc/kritter-tern-dir-pull-conf-mad-handset-service/log/main
        chmod -v 1755 /etc/kritter-tern-dir-pull-conf-mad-handset-service/log
        chmod -v g+s /etc/kritter-tern-dir-pull-conf-mad-handset-service/log
fi
if [ -e /etc/kritter-tern-dir-pull-conf-mad-handset-service/run ]; then
        update-service --add /etc/kritter-tern-dir-pull-conf-mad-handset-service 
fi
