-- This table stores country data as country_code/country_name along with set of ids as generated by different datasources.
CREATE TABLE ui_targeting_country
(
id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
country_code VARCHAR(2) UNIQUE NOT NULL,
country_name VARCHAR(200) UNIQUE NOT NULL,
entity_id_set TEXT NOT NULL,
modified_on TIMESTAMP NOT NULL
)ENGINE=INNODB;
