-- This table stores ispname along with set of ids generated by different geo datasources for a given isp.
CREATE TABLE ui_targeting_isp
(
id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
isp_name VARCHAR(200) NOT NULL,
entity_id_set TEXT NOT NULL,
modified_on TIMESTAMP NOT NULL
)ENGINE=INNODB;
