#!/bin/sh

exec 2>&1

DAEMON=/usr/share/kritter/tern/tern_file_pull/bin/tern_file_pull.py
CONF=/usr/share/kritter/tern/tern_file_pull/conf/sample/

SLEEP=`perl -e "print int(rand(300))"`

echo "Starting in $SLEEP seconds..."
sleep $SLEEP


python ${DAEMON} ${CONF}
